//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un TextTemplate.
//     Generation : 03/14/2018 22:47:54
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using LinqToFile;
using System.Linq;

namespace WinTest
{

  [FileColumn(FieldIndex = 1,Property = "Account_Code",UsePropertyAsName = true,MaxLength = 6,FillChar = '0')]
  [FileColumn(FieldIndex = 2,Property = "A",UsePropertyAsName = true,MaxLength = 9,FillChar = ' ')]
  [FileColumn(FieldIndex = 3,Property = "B",UsePropertyAsName = true,MaxLength = 9,FillChar = ' ')]
  [FileColumn(FieldIndex = 4,Property = "C",UsePropertyAsName = true,MaxLength = 9,FillChar = ' ')]
  public partial class Company
  {
  }
  
  [FileColumn(FieldIndex = 1,Property = "Code_Article",UsePropertyAsName = true,MaxLength = 5)]
  [FileColumn(FieldIndex = 2,Property = "Code_CSP",UsePropertyAsName = true,MaxLength = 2)]
  [FileColumn(FieldIndex = 3,Property = "Pourcent",UsePropertyAsName = true,OutputFormat = "00.000")]
  [FileColumn(FieldIndex = 4,Property = "Date_Application",UsePropertyAsName = true,MaxLength = 8,OutputFormat = "yyyyMMdd")]
  [FileColumn(FieldIndex = 5,Property = "Date_Fin",UsePropertyAsName = true,MaxLength = 8,OutputFormat = "yyyyMMdd")]
  public partial class Remise
  {
  }
  
 	

}


  